version: '3.7'
services:
  postgres:
    image: postgres:12
    container_name: postgres
    ports:
      - '3333:5432'
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_HOST_AUTH_METHOD: ${POSTGRES_HOST_AUTH_METHOD}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres:/var/lib/postgresql/data
  app:
    container_name: app
    links:
      - postgres
    depends_on:
      - postgres    
    ports:
      - '3000:3000'
    build:
      context: .
      dockerfile: Dockerfile  
      args:
        - POSTGRES_URL=${POSTGRES_URL}
        - ENVIROMENT=${ENVIROMENT}
    environment:
      POSTGRES_URL: ${POSTGRES_URL}
      ENVIROMENT: ${ENVIROMENT}
    volumes:
      - ./:/app
      - /node_modules
      - /.next
      - /prisma
volumes: #define our postgres volume used above
  postgres: